exclude: 'docs|node_modules|migrations|.git|.tox|.yaml'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: (^|/).+\.(py|html|sh|css|js)$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ['--line-length=120', '--skip-string-normalization']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: app/learning_languages/config/settings/
        args: ['--max-line-length=120', '--config=setup.cfg']
