version: '3.8'

services:
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    expose:
      - 8080
    volumes:
      - static_volume:/home/app/web/cers/static
    env_file:
      - ./.env.prod
    depends_on:
      - db
    command: gunicorn cers.config.wsgi:application --bind 0.0.0.0:8080
  db:
      restart: always
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/cers/data
      env_file:
        - ./.env.prod.db
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/cers/static
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
