# Generated by Django 4.1.4 on 2022-12-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('cers_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cersuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='cersuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Phone number'),
        ),
    ]
