# Generated by Django 4.1.4 on 2023-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cersuser',
            name='report_on_behalf',
            field=models.BooleanField(default=False),
        ),
    ]
