# Generated by Django 4.1.4 on 2023-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0002_cersuser_report_on_behalf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cersuser',
            name='report_on_behalf',
            field=models.BooleanField(default=False, verbose_name='Report on behalf'),
        ),
        migrations.AlterField(
            model_name='cersuser',
            name='settings',
            field=models.JSONField(blank=True, default={'company': 0}, null=True, verbose_name='Settings'),
        ),
    ]
