# Generated by Django 5.1.5 on 2025-01-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0005_company_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cersuser',
            name='color',
            field=models.CharField(default='', max_length=255, verbose_name='color'),
        ),
    ]
