# Generated by Django 4.1.4 on 2022-12-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0005_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cersuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
