# Generated by Django 5.1.5 on 2025-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0006_cersuser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cersuser',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='color'),
        ),
    ]
