# Generated by Django 4.1.4 on 2022-12-20 20:56

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='user')
    Group.objects.get_or_create(name='manager')
    Group.objects.get_or_create(name='admin')


class Migration(migrations.Migration):
    dependencies = [
        ('cers_auth', '0006_alter_cersuser_is_staff'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
