# Generated by Django 4.1.4 on 2023-02-06 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cers_auth', '0004_alter_cersuser_created_alter_cersuser_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('report_type', models.CharField(choices=[('monthly_report', 'Monthly report')], max_length=50, verbose_name='Report type')),
                ('date_from', models.DateField(verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cers_auth.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Reports generation',
                'verbose_name_plural': 'Reports generation',
            },
        ),
    ]
