# Generated by Django 4.1.4 on 2023-02-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0004_alter_cersuser_created_alter_cersuser_modified_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Report file'),
        ),
        migrations.AlterField(
            model_name='reportgeneration',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cers_auth.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
