# Generated by Django 4.1.4 on 2024-10-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0004_alter_cersuser_created_alter_cersuser_modified_and_more'),
        ('reports', '0002_reportgeneration_report_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgeneration',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cers_auth.company', verbose_name='Company'),
        ),
    ]
