# Generated by Django 5.1.5 on 2025-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportgeneration_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgeneration',
            name='report_type',
            field=models.CharField(choices=[('monthly_report', 'Monthly report'), ('monthly_report_deadline', 'Monthly report deadline')], max_length=50, verbose_name='Report type'),
        ),
    ]
