# Generated by Django 4.1.4 on 2023-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('placed', 'Placed'), ('ordered', 'Ordered'), ('on-site', 'On-site'), ('for release', 'For release'), ('delivered', 'Delivered')], default='placed', max_length=120, verbose_name='Status'),
        ),
    ]
