# Generated by Django 4.1.4 on 2023-01-13 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('mac_address', models.CharField(max_length=255, verbose_name='MAC address')),
                ('number', models.CharField(max_length=255, verbose_name='Computer number')),
                ('operating_system', models.CharField(max_length=255, verbose_name='Operating system')),
                ('office', models.CharField(max_length=120, verbose_name='Office')),
                ('bios_password', models.CharField(max_length=120, verbose_name='Bios password')),
                ('bitlocker', models.CharField(max_length=250, verbose_name='Bitlocker')),
                ('backup', models.BooleanField(default=False, verbose_name='Backup')),
                ('ssd', models.BooleanField(default=False, verbose_name='SSD')),
                ('norton', models.CharField(max_length=70, verbose_name='Norton')),
                ('synology_pass', models.CharField(max_length=255, verbose_name='Synology password')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('vpn', models.BooleanField(default=False, verbose_name='VPN')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
