# Generated by Django 4.1.4 on 2023-01-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_computer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Computer', 'verbose_name_plural': 'Computers'},
        ),
    ]
