# Generated by Django 4.1.4 on 2023-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_computer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='bios_password',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bios password'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='bitlocker',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Bitlocker'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC address'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='norton',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Norton'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Computer number'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='office',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating system'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='synology_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Synology password'),
        ),
    ]
