# Generated by Django 4.1.4 on 2023-01-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_remove_computer_norton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='norton_installed',
            new_name='norton',
        ),
    ]
