# Generated by Django 4.1.4 on 2023-01-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_norton_installed_computer_norton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='vpn',
        ),
    ]
