# Generated by Django 4.1.4 on 2023-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_manufacturer_operatingsystem_processor_powersupply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harddrive',
            options={'verbose_name': 'Hard Drive', 'verbose_name_plural': 'Hard Drives'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name': 'Motherboard', 'verbose_name_plural': 'Motherboards'},
        ),
        migrations.AlterModelOptions(
            name='powersupply',
            options={'verbose_name': 'Power Supply', 'verbose_name_plural': 'Power Supplies'},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'verbose_name': 'Processor', 'verbose_name_plural': 'Processors'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
