# Generated by Django 4.1.4 on 2023-01-27 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0004_alter_cersuser_created_alter_cersuser_modified_and_more'),
        ('hardware', '0011_alter_harddrive_options_alter_memory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motherboard',
            new_name='MotherboardModel',
        ),
        migrations.RenameModel(
            old_name='PowerSupply',
            new_name='PowerSupplyModel',
        ),
        migrations.RenameModel(
            old_name='Processor',
            new_name='ProcessorModel',
        ),
        migrations.AlterModelOptions(
            name='computerset',
            options={'verbose_name': 'Computer set', 'verbose_name_plural': 'Computer sets'},
        ),
        migrations.AlterModelOptions(
            name='harddrive',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name': 'Operating system', 'verbose_name_plural': 'Operating systems'},
        ),
        migrations.RemoveField(
            model_name='computerset',
            name='hard_drive',
        ),
        migrations.RemoveField(
            model_name='computerset',
            name='hard_drive_serial_number',
        ),
        migrations.RemoveField(
            model_name='computerset',
            name='memory_ram',
        ),
        migrations.RemoveField(
            model_name='computerset',
            name='memory_ram_serial_number',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='created',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='id',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='computerset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cers_auth.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='date_of_sale',
            field=models.DateField(verbose_name='Date of sale'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.motherboardmodel', verbose_name='Motherboard'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='motherboard_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motherboard serial number'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.operatingsystem', verbose_name='Operating system'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='power_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.powersupplymodel', verbose_name='Power supply'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='power_supply_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Power supply serial number'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.processormodel', verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='processor_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Processor serial number'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='computerset',
            name='warranty',
            field=models.IntegerField(verbose_name='Warranty'),
        ),
        migrations.CreateModel(
            name='MemoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer')),
            ],
            options={
                'verbose_name': 'Memory Model',
                'verbose_name_plural': 'Memory Models',
            },
        ),
        migrations.CreateModel(
            name='HardDriveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer')),
            ],
            options={
                'verbose_name': 'Hard Drive Model',
                'verbose_name_plural': 'Hard Drive Models',
            },
        ),
        migrations.CreateModel(
            name='GraphicCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer')),
            ],
            options={
                'verbose_name': 'Graphic Card',
                'verbose_name_plural': 'Graphic Cards',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number')),
                ('computer_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.computerset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='harddrive',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.harddrivemodel'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.memorymodel'),
        ),
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.component')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.graphiccardmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('hardware.component',),
        ),
    ]
