# Generated by Django 4.1.4 on 2023-01-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_alter_graphiccard_options_alter_harddrive_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphiccard',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.graphiccardmodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='graphiccardmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='graphiccardmodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.harddrivemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='harddrivemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='harddrivemodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.memorymodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='memorymodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='memorymodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='motherboardmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='motherboardmodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='powersupplymodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='powersupplymodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='processormodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='processormodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
    ]
