# Generated by Django 4.1.4 on 2023-01-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0014_alter_graphiccard_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerset',
            name='operating_system_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating system serial number'),
        ),
    ]
