# Generated by Django 4.1.4 on 2023-02-20 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


def rename_model_field(apps, schema_editor):
    ComputerSet = apps.get_model('hardware', 'ComputerSet')
    ComputerModel = apps.get_model('hardware', 'ComputerModel')
    for computer in ComputerSet.objects.all():
        model, created = ComputerModel.objects.get_or_create(name=computer.model)
        computer.new_model = model
        computer.save()


class Migration(migrations.Migration):
    dependencies = [
        ('hardware', '0016_remove_computerset_operating_system_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Computer model',
                'verbose_name_plural': 'Computer models',
            },
        ),
        migrations.AlterField(
            model_name='computerset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number'),
        ),
        migrations.CreateModel(
            name='SerialNumberConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('number_length', models.PositiveIntegerField(default=5, verbose_name='Number length')),
                ('computer_model',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.computermodel',
                                      verbose_name='Computer model')),
            ],
            options={
                'verbose_name': 'Serial number config',
                'verbose_name_plural': 'Serial number config',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('full_number', models.CharField(max_length=255, verbose_name='Full number')),
                ('number', models.PositiveIntegerField()),
                ('computer_set',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hardware.computerset')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_number',
                                             to='hardware.serialnumberconfig', verbose_name='Serial number config')),
            ],
            options={
                'verbose_name': 'Serial number',
                'verbose_name_plural': 'Serial numbers',
            },
        ),
        migrations.AddField(
            model_name='computerset',
            name='new_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, verbose_name='Model',
                                    to='hardware.computermodel'),
        ),
        migrations.RunPython(rename_model_field),
        migrations.RemoveField(
            model_name='computerset',
            name='model'
        ),
        migrations.RenameField(
            model_name='computerset',
            old_name='new_model',
            new_name='model'
        )

    ]
