# Generated by Django 4.1.4 on 2023-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0017_computermodel_alter_computerset_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumberconfig',
            name='prefix',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='serialnumberconfig',
            name='suffix',
            field=models.CharField(default='', max_length=20),
        ),
    ]
