# Generated by Django 4.1.4 on 2023-07-18 15:53

from django.db import migrations, models
import django.db.models.deletion


def rewrite_company(apps, schema_editor):
    Computer = apps.get_model('hardware', 'Computer')
    for computer in Computer.objects.all():
        if computer.user:
            if computer.user.companies.all().count() == 1:
                computer.company = computer.user.companies.first()
                computer.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cers_auth', '0004_alter_cersuser_created_alter_cersuser_modified_and_more'),
        ('hardware', '0021_graphiccardmodel_driver_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cers_auth.company', verbose_name='Company'),
        ),
        migrations.RunPython(rewrite_company)
    ]
