# Generated by Django 4.1.4 on 2023-03-27 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('logo', models.FileField(upload_to='', verbose_name='logo')),
                ('main_company', models.BooleanField(default=False, verbose_name='main company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
