# Generated by Django 4.1.4 on 2023-03-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0004_alter_cersuser_created_alter_cersuser_modified_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='cers_auth.company', verbose_name='company'),
            preserve_default=False,
        ),
    ]
