# Generated by Django 4.1.4 on 2022-12-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0003_company_alter_cersuser_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
