# Generated by Django 4.1.4 on 2023-07-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyconfig_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfig',
            options={'verbose_name': 'Company config', 'verbose_name_plural': 'Company config'},
        ),
    ]
