# Generated by Django 4.1.4 on 2023-01-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='access_to_client',
            field=models.BooleanField(default=False, verbose_name='Access to the client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cers_auth.company', verbose_name='Company'),
        ),
    ]
