# Generated by Django 4.1.4 on 2022-12-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
