# Generated by Django 4.1.4 on 2023-01-10 21:24

from django.db import migrations
from django.db.models import F


def correct_close_date(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    Ticket.objects.filter(status='close').update(closed_date=F('deadline'))


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0003_ticket_closed_date'),
    ]

    operations = [
        migrations.RunPython(correct_close_date)
    ]
