# Generated by Django 4.1.4 on 2022-12-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketClosedAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Closed ticket',
                'verbose_name_plural': 'Closed tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='TicketOpenAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Open ticket',
                'verbose_name_plural': 'Open tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.ticket',),
        ),
    ]
