# Generated by Django 4.1.4 on 2022-12-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketclosedadmin_ticketopenadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketclosedadmin',
            options={'verbose_name': 'Closed ticket +', 'verbose_name_plural': 'Closed tickets +'},
        ),
        migrations.AlterModelOptions(
            name='ticketopenadmin',
            options={'verbose_name': 'Open ticket +', 'verbose_name_plural': 'Open tickets +'},
        ),
    ]
