# Generated by Django 4.1.4 on 2022-12-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketclosedadmin_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketClosedAdmin',
        ),
        migrations.DeleteModel(
            name='TicketOpenAdmin',
        ),
    ]
