# Generated by Django 4.1.4 on 2023-01-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cers_auth', '0008_auto_20221228_0909'),
        ('tickets', '0008_delete_ticketclosedadmin_delete_ticketopenadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cers_auth.company'),
        ),
    ]
